lxd:
    resource: "@LxdBundle/Controller/"
    type:     annotation
    prefix:   /

api:
    resource: '.'
    type:     'api_platform'

file_bundle:
    resource: "@FileBundle/Resources/config/routing.yml"
    prefix:   '/api'