api:
    resource: '.'
    type:     'api_platform'

file_bundle:
    resource: "@FileBundle/Resources/config/routing.yml"
    prefix:   '/'

lxd_bundle:
    resource: "@LxdBundle/Resources/config/routing.yml"
    prefix:   '/lxd'
