types:
    Book:
        parent: false
        properties:
            isbn: ~
            name: { nullable: false }
            description: { nullable: false }
            author: { range: Text, nullable: false }
            dateCreated: { nullable: false }
    Review:
        parent: false
        properties:
            reviewBody: ~
            rating: { range: Integer, nullable: false } # This is a custom field that doesn't exist in the vocab
            itemReviewed: { range: Book, nullable: false, cardinality: '(*..1)' }
