Mysiar\LxdBundle\Model\Containers\Containers:
    properties:
        statusCode:
            identifier: true
    collectionOperations:
        get:
            method: 'GET'
            route_name: 'Mysiar\LxdBundle\Action\Containers\GetCollection'
    itemOperations: []
