Mysiar\LxdBundle\Model\Info\Info:
    properties:
        statusCode:
            identifier: true
    collectionOperations:
        get:
            method: 'GET'
            route_name: 'Mysiar\LxdBundle\Action\Info'
    itemOperations: []
