services:
    _defaults:
        autowire: true

    Mysiar\LxdBundle\Config:
        class: Mysiar\LxdBundle\Config
        factory: ['Mysiar\LxdBundle\ConfigFactory', createConfig]
        arguments: ['%lxd%']

    Mysiar\LxdBundle\Client:
        class: Mysiar\LxdBundle\Client

    Mysiar\LxdBundle\Action\Info:
        class: Mysiar\LxdBundle\Action\Info
